### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by KiWiLss** [yhaolpz/FixedFloatWindow#1]
在模拟器上,7.1会直接崩溃,真机不知道会怎么样?

**Comment by yhaolpz** [comment]
@KiWiLss   声明权限了吗

**Comment by KiWiLss** [comment]
<uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT"/>
    
    <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
    
    <uses-permission android:name="com.android.launcher.permission.UNINSTALL_SHORTCUT" />
这三个权限

**Comment by KiWiLss** [comment]
这是我下载下来直接运行的日志
FATAL EXCEPTION: main
                                                                                 Process: com.example.yhao.fixedfloatwindow, PID: 4180
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.yhao.fixedfloatwindow/com.example.fixedfloatwindow.FixedFloatActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                                  Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:356)
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:325)
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.onPostCreate(AppCompatDelegateImplV9.java:173)
                                                                                     at android.support.v7.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:97)
                                                                                     at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1199)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:154)

**Comment by yhaolpz** [comment]
@KiWiLss  不好意思，在 style 下修改为 Theme.AppCompat 包下的主题可以暂时解决这个问题，我会尽快更新这个问题。

**Comment by yhaolpz** [comment]
@KiWiLss  7.1及以上版本应该声名的悬浮窗权限是： <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />

**Comment by yhaolpz** [comment]
@KiWiLss 已修复此bug

**Comment by KiWiLss** [comment]
谢谢
